In [78]:
import os
import numpy as np
from PIL import Image
import cv2

channel0_path = 'OUT/shift0/1.jpg'
channel0 = Image.open(channel0_path)

channel1_path = 'OUT/shift1/1.jpg'
channel1 = Image.open(channel1_path)

channel2_path = 'OUT/shift2/1.jpg'
channel2 = Image.open(channel2_path)

x_0 = np.array(channel0)
print(x_0)
print(x_0.shape)

x_1 = np.array(channel1)
print(x_1)
print(x_1.shape)

x_2 = np.array(channel2)
print(x_2)
print(x_2.shape)

combine = cv2.merge([x_0, x_1, x_2]) # rgb -> red(r) : x_0, green(g): x_1, blue(b): x_2

combine = np.array(combine).reshape(256,256,3)
print(combine.shape)

img_2 = Image.fromarray(combine)
img_2.show()



[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(256, 256)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(256, 256)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(256, 256)
(256, 256, 3)


In [65]:
!pip install torchvision

     |████████████████████████████████| 1.3 MB 6.0 MB/s eta 0:00:01
     |████████████████████████████████| 137.7 MB 98 kB/s  eta 0:00:01   |█▉                              | 7.7 MB 1.1 MB/s eta 0:02:01     |███▋                            | 15.6 MB 325 kB/s eta 0:06:15     |███████▍                        | 31.8 MB 345 kB/s eta 0:05:07     |███████▊                        | 33.1 MB 335 kB/s eta 0:05:12     |██████████████████████████▌     | 114.1 MB 361 kB/s eta 0:01:06     |███████████████████████████▋    | 118.8 MB 314 kB/s eta 0:01:01
